name = "worker-for-notion"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-12-19"

[build]
command = "pnpm install && pnpm build"
[build.upload]
format = "service-worker"
